<?php

return [
    '/adminHome' => 'admin/admin.php',
    '/empdetails' => 'admin/admin.php',
    '/education' => 'admin/education.php',
    '/familyDetails' => 'admin/familyDetails.php',
    '/experience' => 'admin/experience.php',
    '/update' => 'admin/adminUpdateUser.php',
    '/delete' => 'admin/deleteUser.php',
    '/updateuser' => 'admin/updateuser.php',
    '/createUserView' => 'admin/createuser.view.php',
    '/createUser' => 'admin/createuser.php',
    '/' => 'session/login.php',
    '/store' => 'session/store.php',
    '/login' => 'session/login.php',
    '/logout' => 'session/logout.php',
    '/empHome' => 'session/employeeHome.php',
    '/access' => 'admin/accessControl.php',
    '/adminDeleteRecord' => 'admin/editAndUpdate/adminDeleteRecord.php',
    '/adminViewEdit' => 'admin/editAndUpdate/adminViewEdit.view.php',
    '/adminUserUpdate' => 'admin/editAndUpdate/adminUserUpdate.php',
    '/userUpdate' => 'session/userUpdate.php',
    '/userDeleteRecord' => 'session/userDeleteRecord.php',
];  